import type { JSDOM } from "jsdom";

/** Trims and remove final semicolons in JS files */
export function jsRemoveEndingSemicolons(code: string | null | undefined) {
  return code ? code.trimStart().replace(/[\s;]+$/, "") : "";
}

/** Reduces HTML size by removing </body> and </html> at the end. */
export function htmlStripBodyHtmlEndTags(html: string) {
  return html.replace(/(\s*<\s*\/\s*(html|body)\s*>\s*)*$/i, "");
}

/** Removes all external scripts and css from an HTML. */
export function domRemoveExternalCssAndScripts(dom: JSDOM) {
  Array.from(dom.window.document.querySelectorAll("script[src], link[href]")).forEach((el) => el.remove());
}

export const browserPureFunctions = [
  "Math.abs",
  "Math.acos",
  "Math.acosh",
  "Math.asin",
  "Math.asinh",
  "Math.atan",
  "Math.atanh",
  "Math.atan2",
  "Math.ceil",
  "Math.cbrt",
  "Math.expm1",
  "Math.clz32",
  "Math.cos",
  "Math.cosh",
  "Math.exp",
  "Math.floor",
  "Math.fround",
  "Math.hypot",
  "Math.imul",
  "Math.log",
  "Math.log1p",
  "Math.log2",
  "Math.log10",
  "Math.max",
  "Math.min",
  "Math.pow",
  "Math.random",
  "Math.round",
  "Math.sign",
  "Math.sin",
  "Math.sinh",
  "Math.sqrt",
  "Math.tan",
  "Math.tanh",
  "Math.trunc",
  "Object.getOwnPropertyDescriptor",
  "Object.getOwnPropertyDescriptors",
  "Object.getOwnPropertyNames",
  "Object.getOwnPropertySymbols",
  "Object.is",
  "Object.create",
  "Object.getPrototypeOf",
  "Object.isExtensible",
  "Object.isFrozen",
  "Object.isSealed",
  "Object.keys",
  "Object.entries",
  "Object.fromEntries",
  "Object.values",
  "Reflect.apply",
  "Reflect.get",
  "Reflect.getOwnPropertyDescriptor",
  "Reflect.has",
  "Reflect.isExtensible",
  "Reflect.ownKeys",

  "Object",
  "Function",
  "Array",
  "Number",
  "parseFloat",
  "parseInt",
  "Boolean",
  "String",
  "Symbol",
  "Date",
  "Promise",
  "RegExp",
  "Error",
  "TypeError",
  "SyntaxError",
  "EvalError",
  "RangeError",
  "ReferenceError",
  "SyntaxError",
  "TypeError",
  "URIError",
  "ArrayBuffer",
  "Uint8Array",
  "Int8Array",
  "Uint16Array",
  "Int16Array",
  "Uint32Array",
  "Int32Array",
  "Float32Array",
  "Float64Array",
  "Uint8ClampedArray",
  "BigUint64Array",
  "BigInt64Array",
  "DataView",
  "Map",
  "BigInt",
  "Set",
  "WeakMap",
  "WeakSet",
  "Proxy",
  "decodeURI",
  "decodeURIComponent",
  "encodeURI",
  "encodeURIComponent",
  "escape",
  "unescape",
  "isFinite",
  "isNaN",
  "find",
  "btoa",
  "atob",
];
