export const MODEL_ID_SKY = 0;

export const MODEL_ID_STATIC_WORLD = 1;

export const MODEL_ID_BOAT0 = 2;

export const MODEL_ID_BOAT1 = 3;

export const MODEL_ID_GATE0 = 4;

export const MODEL_ID_GATE1 = 5;

export const MODEL_ID_GATE2 = 6;

export const MODEL_ID_GATE3 = 7;

export const MODEL_ID_LEVEL1_CENTRAL_PLATFORM = 8;

export const MODEL_ID_LEVEL2_BLACK_PLATFORM0 = 9;

export const MODEL_ID_LEVEL2_BLACK_PLATFORM1 = 10;

export const MODEL_ID_LEVEL2_CENTRAL_PLATFORM = 11;

export const MODEL_ID_TRIANGLE_PLATFORM = 12;

export const MODEL_ID_LEVEL2_MINI_PLATFORM_VERTICAL = 13;

export const MODEL_ID_LEVEL2_MINI_PLATFORM_HORIZONTAL = 14;

export const MODEL_ID_LEVEL2_HEX_CORRIDOR_DOOR = 15;

export const MODEL_ID_LEVEL2_ROTATING_HEX_CORRIDOR = 16;

export const MODEL_ID_ELEVATORS0 = 17;

export const MODEL_ID_ELEVATORS1 = 18;

export const MODEL_ID_MONUMENT = 19;

export const MODEL_ID_PUSHING_ROD0 = 20;

export const MODEL_ID_PUSHING_ROD1 = 21;

export const MODEL_ID_PUSHING_ROD2 = 22;

export const MODEL_ID_OSCILLATING_HEX_PAD0 = 23;

export const MODEL_ID_OSCILLATING_HEX_PAD1 = 24;

export const MODEL_ID_OSCILLATING_HEX_PAD2 = 25;

export const MODEL_ID_OSCILLATING_HEX_PAD3 = 26;

export const MODEL_ID_DONUT_PAD = 27;

export const MODEL_ID_ROTATING_PLATFORM0 = 28;

export const MODEL_ID_ROTATING_PLATFORM1 = 29;

export const MODEL_ID_ROTATING_PLATFORM2 = 30;

export const MODEL_ID_ROTATING_PLATFORM3 = 31;

export const MODEL_ID_JUMPING_PAD0 = 32;

export const MODEL_ID_JUMPING_PAD1 = 33;

export const MODEL_ID_JUMPING_PAD2 = 34;

export const MODEL_ID_PENDULUMS = 35;

export const MODEL_ID_FLOATING_ELEVATOR_PAD = 36;

export const MODEL_ID_PLAYER_BODY = 37;

export const MODEL_ID_PLAYER_LEG0 = 38;

export const MODEL_ID_PLAYER_LEG1 = 39;

export const MODEL_ID_SOUL_COLLISION = 40;

export const MODEL_ID_SOUL = 41;

export const MODEL_ID_LEVER = 42;

export const MODEL_IDS = {
  MODEL_ID_SKY,
  MODEL_ID_STATIC_WORLD,
  MODEL_ID_BOAT0,
  MODEL_ID_BOAT1,
  MODEL_ID_GATE0,
  MODEL_ID_GATE1,
  MODEL_ID_GATE2,
  MODEL_ID_GATE3,
  MODEL_ID_LEVEL1_CENTRAL_PLATFORM,
  MODEL_ID_LEVEL2_BLACK_PLATFORM0,
  MODEL_ID_LEVEL2_BLACK_PLATFORM1,
  MODEL_ID_LEVEL2_CENTRAL_PLATFORM,
  MODEL_ID_TRIANGLE_PLATFORM,
  MODEL_ID_LEVEL2_MINI_PLATFORM_VERTICAL,
  MODEL_ID_LEVEL2_MINI_PLATFORM_HORIZONTAL,
  MODEL_ID_LEVEL2_HEX_CORRIDOR_DOOR,
  MODEL_ID_LEVEL2_ROTATING_HEX_CORRIDOR,
  MODEL_ID_ELEVATORS0,
  MODEL_ID_ELEVATORS1,
  MODEL_ID_MONUMENT,
  MODEL_ID_PUSHING_ROD0,
  MODEL_ID_PUSHING_ROD1,
  MODEL_ID_PUSHING_ROD2,
  MODEL_ID_OSCILLATING_HEX_PAD0,
  MODEL_ID_OSCILLATING_HEX_PAD1,
  MODEL_ID_OSCILLATING_HEX_PAD2,
  MODEL_ID_OSCILLATING_HEX_PAD3,
  MODEL_ID_DONUT_PAD,
  MODEL_ID_ROTATING_PLATFORM0,
  MODEL_ID_ROTATING_PLATFORM1,
  MODEL_ID_ROTATING_PLATFORM2,
  MODEL_ID_ROTATING_PLATFORM3,
  MODEL_ID_JUMPING_PAD0,
  MODEL_ID_JUMPING_PAD1,
  MODEL_ID_JUMPING_PAD2,
  MODEL_ID_PENDULUMS,
  MODEL_ID_FLOATING_ELEVATOR_PAD,
  MODEL_ID_PLAYER_BODY,
  MODEL_ID_PLAYER_LEG0,
  MODEL_ID_PLAYER_LEG1,
  MODEL_ID_SOUL_COLLISION,
  MODEL_ID_SOUL,
  MODEL_ID_LEVER,
};
