import { LEVERS_COUNT, MODELS_WITH_FULL_TRANSFORM, MODELS_WITH_SIMPLE_TRANSFORM, SOULS_COUNT } from "./models";

export const transformsBuffer = new Float32Array(
  (4 * (MODELS_WITH_FULL_TRANSFORM + LEVERS_COUNT + SOULS_COUNT) + MODELS_WITH_SIMPLE_TRANSFORM) * 4,
);
