/** Map of uniforms and globals to be renamed in all shaders at build time */
export default {
  projectionMatrix: "a",
  viewMatrix: "b",
  worldMatrix: "c",
  aColor: "d",
  aNormal: "e",
  aPosition: "f",
  csm_texture0: "g",
  csm_texture1: "h",
  csm_matrix0: "i",
  csm_matrix1: "j",
  viewPos: "k",
  Color: "l",
  FragPos: "m",
  UntransformedFragPos: "n",
  VNormal: "o",
  groundTexture: "q",
  iResolution: "j",
};
