export default {
  projectionMatrix: "A",
  viewMatrix: "B",
  aColor: "D",
  aNormal: "E",
  aPosition: "F",
  depthTextures: "G",
  lightDir: "H",
  csm_matrices: "I",
  viewPos: "J",
  Color: "K",
  FragPos: "L",
  Normal: "M",
  modelViewMatrix: "N",
};
